GET  http://localhost:3001/api/notes


###
DELETE http://localhost:3001/api/notes/1


###
POST http://localhost:3001/api/notes
Content-Type: application/json

[
  {
    "content": "I'm very good",
    "important": true
  },
  {
    "content": "",
    "important": true
  },
  {
    "content": "I hate writting spacghetti code from AI",
    "important": false
  },
  {
    "content": "I'm a married man, having one cute kid as well ",
    "important": true
  }
]


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Ok, we are going really good, but only for those students that can feel the progress "
}