POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "CodeSmithNazim",
  "email": "codeSmithNazim@gmail.com",
  "password": "1232(&^^^%!232fhgfhf./,.'l'8",
  "notes": "6a871f013799ccd479e4e1e7"
}


### 
DELETE http://localhost:3000/api/users